# https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai
dist: trusty
sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "10"
cache: yarn

# env:
#   global:
#     - SAUCE_USERNAME=valorkin
#     - SAUCE_ACCESS_KEY=aeaf806e-ad5c-484b-a8fe-4b4b9f54e99a

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn
  - yarn lerna run clean
  - yarn lerna bootstrap
  - yarn workspace ng2-dragula test-coverage
  - yarn workspace ng2-dragula build
  - yarn workspace demo build --prod --progress=false

after_success:
  - yarn workspace ng2-dragula codecov

deploy:
  provider:     pages
  fqdn:         valor-software.com
  skip_cleanup: true
  local_dir:    modules/demo/dist/demo
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

# addons:
  # sauce labs tunel connector (read more https://docs.travis-ci.com/user/sauce-connect/ )
  # sauce_connect: true
  # firefox: "latest"
  # apt:
  #   sources:
  #   - ubuntu-toolchain-r-test
  #   # required by node-gyp to build some packages
  #   packages:
  #   - g++-4.8
